# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MIME-Charset
version:      1.005
version_from: Charset.pm
installdirs:  site
requires:
    Encode:                        1.98
    Test:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
